# script written by Shadowdara

# MAIN FILE

import os
import sys

import convert_list
import delete_autogenerated

# variables
ini_info2 = 'required.ini'

choice_text = """What do you want to do?
    (Enter) to -> 2 & 1
    0 to exit
    1 to convert the csv table
    2 to delete the autogenerated files

Your choise: """


# functions
def start(choice):
    if choice == '':
        delete_autogenerated.delete_files(path, ini_info2)
        convert_list.create_files(path)
    
    elif choice == '0':
        sys.exit(0)
    
    elif choice == '1':
        convert_list.create_files(path)

    elif choice == '2':
        delete_autogenerated.delete_files(path, ini_info2)

# run on execution
if __name__ == '__main__':
    path = os.path.dirname(os.path.abspath(__file__))

    print("weuritz8u's Project List Script\n")

    try:
        delete_autogenerated.delete_files(path, ini_info2)
    except: print("Error")

    while True:
        choice = input(choice_text)
        start(choice)
